### ISSUE TITLE
Possible bug with a jobs parameters not coming through.

### ISSUE THREAD

**Issue by HexTank** [jenkinsci/poll-mailbox-trigger-plugin#11]
If you have a job that is parameterized and set to some default values, if you trigger a build using the poll mailbox trigger then these parameters are never exposed to the job, firing the same job manually then these parameters do get exposed and can be observed with a bit of groovy script.

```
import hudson.model.*
import jenkins.model.*

build?.actions.find{ it instanceof ParametersAction}?.parameters.each {
  if(!it.name.startsWith('pmt_')) {
    println("${it.name}=${it.value}")
  }
}
```

**Comment by HexTank** [comment]
It seems there is a way to do this with some caveats (bear with me as my Java experience is with Groovy), Something like the following between actions.addall and actions.add in startJob.  If job parameters are in the email it will try use those, else will use the defaults.

```
if(job.isParameterized()) {
  job.getProperty(ParametersDefinitionProperty.class).getParameterDefinitions().each {
    def JobParameterValue = it.getDefaultParameterValue()
    if(envVars.containsKey(it.getName())) {
      JobParameterValue = it.createValue(envVars[it.getName()])
      envVars.remove(it.getName())
    }
    // add param to list
  }
}
```

Caveats being, some ParameterValues don't accept string for createValue and don't make sense to either, but as most of the polling tasks use default values only, maybe this plugin should only fill in what it can and use default values in other areas.

**Comment by nickgrealy** [comment]
Looks good, fancy trying your hand at a pull request?

**Comment by HexTank** [comment]
Yes, I have some code ready to be tested, once I know it's behaving I'll send a pull request.

**Comment by HexTank** [comment]
Pull request added #12

**Comment by nickgrealy** [comment]
Pull request merged.
