### ISSUE TITLE
Confirmation email on receive email

### ISSUE THREAD

**Issue by nickgrealy** [jenkinsci/poll-mailbox-trigger-plugin#14]
It'd be good if I received a confirmation email, when my trigger email is processed, so that I know everything worked. 
e.g.

> RE: Jenkins > Publish @ 12pm
> 
> A Jenkins job has been successfully scheduled for 12pm, with the following parameters:
> app=poll-mailbox-trigger-plugin
> env=dev
> version=1.2.3

**Comment by nickgrealy** [comment]
I haven't had any requests for this feature... will only build it if it's "in demand".

**Comment by vijaychandra24** [comment]
Please consider this
