### ISSUE TITLE
Variables like $pmt_from, $subject, $subjectContains is not working.

### ISSUE THREAD

**Issue by deepu7bn** [jenkinsci/poll-mailbox-trigger-plugin#19]
### Steps to reproduce

How can we reproduce the issue
1. Create a Job and configure poll trigger.
2. Add editable email notification and add the following $pmt_from, $subject, $subjectContains.
3. Now trigger the job with a email, now the email doesn't go to  the job trigger ($pmt_from).
### Expected behaviour

The email should go to job trigger ($pmt_from).
### Actual behaviour

Email trigger fails Error sending to the following INVALID addresses: $pmt_from"
### Server configuration

**Operating system**: Windows 2012 server 

**Jenkins Version**: 2.15

**Plugin Version**:     1.022
### Additional Steps/Questions
- [x] Can you please provide all the configuration details you're using (hide sensitive fields) and any other information which may help? (does it match the [examples here](https://github.com/jenkinsci/poll-mailbox-trigger-plugin#office-365)?)
- [Yes ] Do you know if you're you able to connect to to your mail server via IMAP?
- [ Success] What log messages do you receive, when you press the "Test Connection" button?
- [ Yes] Have you followed the [troubleshooting section on the plugin page](https://github.com/jenkinsci/poll-mailbox-trigger-plugin#troubleshooting)?

If you're feeling ambitious, you can also try [setting up a LogRecorder for the Jenkins plugin](https://wiki.jenkins-ci.org/display/JENKINS/Logging) (the logger package name will be something like "org.jenkinsci.plugins.pollmailboxtrigger"). This may provide extra insight into why your issue is occurring.

**Comment by nickgrealy** [comment]
My apologies, I tested this with a pre v2 (`1.629`) version of Jenkins - which passed.

Testing with post v2 (`2.7.1`) I was able to reproduce the issue.

**Comment by nickgrealy** [comment]
### Current workarounds

Do one of the following:
- explicitly add parameter variable (names) to the jobs (they will be updated by the plugin)
- define a `-Dhudson.model.ParametersAction.safeParameters=pmt_from,pmt_replyTo,etc` property whitelist
- define a `-Dhudson.model.ParametersAction.keepUndefinedParameters=true` property

### See also
- https://groups.google.com/forum/#!topic/jenkinsci-dev/-gl9_lE546Q
- https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2016-05-11
- https://wiki.jenkins-ci.org/display/JENKINS/Plugins+affected+by+fix+for+SECURITY-170

**Comment by nickgrealy** [comment]
Missing env vars fixed in commit https://github.com/jenkinsci/poll-mailbox-trigger-plugin/commit/d0154dab63dc3a5978ebcbcd6aaa6d98212009cf

@deepu7bn , are you happy for that this is fixed, and can be released?
https://github.com/jenkinsci/poll-mailbox-trigger-plugin/releases/tag/1.024-SNAPSHOT

**Comment by deepu7bn** [comment]
Issue is fixed and working fine. thanks nickgrealy :+1:

**Comment by michaelrnz** [comment]
Thanks heaps @nickgrealy :) Tested here as well and my bacon is saved, have a coffee!
