### ISSUE TITLE
Jenkins 2.7.1 LTS Support

### ISSUE THREAD

**Issue by nickgrealy** [jenkinsci/poll-mailbox-trigger-plugin#20]
Since Jenkins v2 has been released, the plugin no longer injects the `pmt_*` variables (as build parameters).

The plugin needs to be updated (and tested) to (only?) support the latest `LTS` (currently `2.7.1`).

**Comment by nickgrealy** [comment]
Duplicate of https://github.com/jenkinsci/poll-mailbox-trigger-plugin/issues/19

**Comment by nickgrealy** [comment]
### Current workarounds

Do one of the following:
- explicitly add parameters to their jobs (they will be updated by the plugin)
- define a `-Dhudson.model.ParametersAction.safeParameters=pmt_from,pmt_replyTo,etc` property whitelist
- define a `-Dhudson.model.ParametersAction.keepUndefinedParameters=true` property

### See also
- https://groups.google.com/forum/#!topic/jenkinsci-dev/-gl9_lE546Q
- https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2016-05-11
- https://wiki.jenkins-ci.org/display/JENKINS/Plugins+affected+by+fix+for+SECURITY-170

**Comment by nickgrealy** [comment]
Missing env vars fixed in commit https://github.com/jenkinsci/poll-mailbox-trigger-plugin/commit/d0154dab63dc3a5978ebcbcd6aaa6d98212009cf

Ready for release

**Comment by vijaychandra24** [comment]
Since Jenkins v2 has been released, the plugin no longer injects the pmt_* variables (as build parameters 
So if pmt variables not supported how can we overcome previous requirement trigger based on email from ??

**Comment by nickgrealy** [comment]
Hi @vijaychandra24,

Thanks for raising this issue.

Can you please re-test using the latest plugin version ([1.026](https://github.com/jenkinsci/poll-mailbox-trigger-plugin/releases/tag/1.026)) - and if you are still encountering issues, please raise a new issue, providing [as much information as possible](https://github.com/jenkinsci/poll-mailbox-trigger-plugin/blob/master/.github/ISSUE_TEMPLATE.md).

I know for certain that the plugins supports Jenkins LTS 2.7.1 (I just tested now), so perhaps if you are not using version 2.7.1, you could consider moving to this Jenkins version.

Kind regards,

Nick Grealy
