### ISSUE TITLE
Office365 behind SSO

### ISSUE THREAD

**Issue by suseendare** [jenkinsci/poll-mailbox-trigger-plugin#28]
hi,

In our organization, we use SSO based authentication to access e-mails in Office 365.
How do I use this plugin to monitor mailbox using SSO?

Thanks!

**Comment by nickgrealy** [comment]
Hi @suseendare ,

I'm not sure to be honest - I'm not familiar with SSO, and the way I understand it, there are many SSO applications/implementations. At the end of the day though, the SSO will still be authenticating with Office365 (somehow) - I imagine you can still login to Office365 using credentials? (have you tried?)

If we had more detail, someone (out there) might be able to help?

Which SSO software are you using:

- [Microsoft Online Services Sign-In Assistant (MOS SIA)](https://technet.microsoft.com/en-us/library/jj631606.aspx)
- [Active Directory Federation Services (ADFS)](https://technet.microsoft.com/en-us/library/jj631606.aspx)
- ??

Kind regards,

Nick

**Comment by nickgrealy** [comment]
No response, Closing issue.
