### ISSUE TITLE
'Download attachments' behaviour should be configurable

### ISSUE THREAD

**Issue by nickgrealy** [jenkinsci/poll-mailbox-trigger-plugin#3]
As a user, I want to be able to enable downloading attachments, so that I can use them in my build.

As a user, I want to be able to DISable downloading attachments, so that I can improve the speed of triggering builds and because attachments aren't required in my build.

**Comment by arghya18** [comment]
hi,
can you please include configurable directory please, sometimes we need to overwrite downloaded files.
