### ISSUE TITLE
imap server and proxy with authentification

### ISSUE THREAD

**Issue by vinogradoff** [jenkinsci/poll-mailbox-trigger-plugin#30]
Is it possible to configure a proxy with authentification in your plugin?

I have found:
mail.imap.socks.host &
mail.imap.socks.port settings, but no property for proxy's username/password...

Could you please help?

**Comment by nickgrealy** [comment]
Hi @vinogradoff ,

From this [one comment here](https://stackoverflow.com/a/38253983/782034), it sounds like JavaMail (the underlying library) doesn't support proxy authentication (only anonymous proxies are supported).

I don't have any experience connecting Java applications via socks proxies with authentication, but if you can find an example on how to do so, I'll do my best to incorporate it into the code base.

Kind regards,
Nick
