### ISSUE TITLE
Multiple Triggers

### ISSUE THREAD

**Issue by omegadash** [jenkinsci/poll-mailbox-trigger-plugin#31]
Would it be possible to build multiple parameterized jobs from a single email?

**Comment by huehnerlady** [comment]
you could have a super job which injects all needed parameters and then triggers multiple builds.

**Comment by nickgrealy** [comment]
@omegadash - I'd go with @huehnerlady's suggestion, of having a "parent" job, responsible for triaging and triggering any number of child builds.

Does this solve your question?
