### ISSUE TITLE
Add code to download email attachments.

### ISSUE THREAD

**Issue by nickgrealy** [jenkinsci/poll-mailbox-trigger-plugin#4]
As a user, I want the plugin to download email attachments, so that I can use them in my build.

**Comment by nickgrealy** [comment]
Code submitted - https://github.com/jenkinsci/poll-mailbox-trigger-plugin/commit/511659952d2e0cdd07033739debbc99ce36b9aa0

TODO: complete acceptance tests.

**Comment by nickgrealy** [comment]
TODO: add documentation

**Comment by sujitsrinivasan** [comment]
Hi @nickgrealy , 

Can you please advice if the the concept of Download attachment onto a specific directory is been incorporated as you discussed in  https://issues.jenkins.io/browse/JENKINS-27575

I just wanted to know where does %pmt_attachmentsDirectory% directory reside ?

Thanks
