### ISSUE TITLE
Enhancement: Add the ability to filter against the User who sent the email

### ISSUE THREAD

**Issue by alexanderrtaylor** [jenkinsci/poll-mailbox-trigger-plugin#52]
### Issue:
We would like to have a filter against the user who sent the email as well as the subject. This would stop builds from happening if the subject comes up in a non-authorized email or with a reply-type email

### Expected behaviour
I would hope that the plugin would also have a form which would allow particular emails to be "authorized" and the plugin would check for the subject and who sent the email

### Actual behaviour
Right now the plugin only checks on the subject

### Server configuration
Any

### Additional Steps/Questions

These I feel like I can ignore since this is a net new enhancement rather than a bug/issue

**Comment by nickgrealy** [comment]
Hi @alexanderrtaylor ,
I'm not maintaining this plugin (looking for an active maintainer), but you might want to consider the workaround (use "Choice" parameter) from this issue -> https://github.com/jenkinsci/poll-mailbox-trigger-plugin/issues/17 (also, this might be a duplicate of that issue, but I'll let you close this ticket).
Kind regards,
Nick

**Comment by alexanderrtaylor** [comment]
Will do and thanks @nickgrealy
